services:

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - data_net

  nifi:
    build: ./nifi
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_SENSITIVE_PROPS_KEY=pUaEVgyGKT61fMCAWNbjJPMwAcQDuDj4
    volumes:
      - ./data:/data
      - ./drivers/postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar
    depends_on:
      - postgres
    networks:
      - data_net

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=client
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./spark:/opt/spark-app
      - ./drivers/postgresql-42.7.3.jar:/opt/spark-app/postgresql-42.7.3.jar
    depends_on:
      - nifi
    networks:
      - data_net
    command: >
      bash -c "
        /opt/wait-for-table.sh postgres 5432 ${POSTGRES_DB} ${POSTGRES_USER} ${POSTGRES_PASSWORD} raw_bitcoin_data &&
        spark-submit --jars /opt/spark-app/postgresql-42.7.3.jar /opt/spark-app/transform_bitcoin_data.py"

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - data_net
    command: >
      bash -c "
        /opt/wait-for-table.sh postgres 5432 ${POSTGRES_DB} ${POSTGRES_USER} ${POSTGRES_PASSWORD} aggregated_bitcoin_data &&
        streamlit run app.py --server.port=8501 --server.address=0.0.0.0"

networks:
  data_net:
    driver: bridge
